import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync, renameSync, watch, writeFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
UNreader - an e-book reader plugin for Obsidian
*/
`;

const prod = process.argv[2] === "production";

/** dev 专用：把每次成功构建同步进本机 Obsidian vault（`npm run deploy` 的同一份实现）。
 *
 *  **必须惰性且可失败**：`scripts/` 是开发机工具，不进公开镜像仓库（那里有用户的
 *  绝对路径），所以提交给官方市场的仓库里**没有**这个文件。曾经的顶层
 *  `import ... from "./scripts/deploy.mjs"` 让 `npm run build` 在干净环境里直接
 *  `ERR_MODULE_NOT_FOUND` 死掉（2026-09-20 上架构建校验报的错就是这个）。
 *  现在：生产构建根本不碰它；dev 缺文件时降级为「只构建、不同步」，不炸构建。 */
let deployToVaults = () => 0;
if (!prod) {
	try {
		({ deployToVaults } = await import("./scripts/deploy.mjs"));
	} catch {
		console.warn("[deploy] 未找到 scripts/deploy.mjs —— dev 自动同步已关闭（不影响 `npm run build`）");
	}
}

/** dev watch 期间把每次成功构建同步进 Obsidian vault。
 *
 *  此前 `npm run dev` 只写仓库根目录的 `main.js`，vault 里还是上一次 `npm run deploy`
 *  的旧产物 —— 于是「改了代码 → 重载插件 → 行为还是旧的」，而且**不会有任何提示**：
 *  AGENTS.md 的调试流程（dev 监听 → Obsidian 重载）默认产物会自动到位，实际并没有。
 *  2026-09-18 的「迁移资料文件夹不生效」就是这么来的（vault 里跑的是 21:44 的旧 bundle，
 *  新迁移代码 22:10 才构建，从未同步）。只同步、不改动仓库产物，构建失败时不同步。 */
const autoDeploy = {
	name: "unreader-auto-deploy",
	setup(build) {
		build.onEnd(result => {
			if (result.errors.length) return;
			deployToVaults({ quiet: true });
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@electron/remote",
		// vendor/foliate-js/view.js 用 `await import('./pdf.js')` 惰性加载 PDF 适配器。
		// PDF 已整体移除（适配器文件亦已删除），保留 external 让 esbuild 不去解析这个
		// 永远走不到的路径——否则构建期会因找不到文件而报错。
		"./pdf.js",
		...builtinModules,
	],
	format: "cjs",
	// es2022：Obsidian 使用的 V8 完整支持，无需降级打包。
	// （PDF 移除后已无 vendor 顶层 await 需求，保持 es2022 以免无谓的兼容性回退）
	target: "es2022",
	logLevel: "info",
	loader: {
		".jpg": "dataurl",
		".jpeg": "dataurl",
		".png": "dataurl",
		// CSS 以文本内联进 bundle（CJS 下无法用 import.meta.url 定位外部资源）。
		// 原为 PDF 查看器样式所加；PDF 移除后暂无消费方，保留作通用能力（无副作用）
		".css": "text",
	},
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// 生产构建不自动写 vault：`npm run release`/CI 不应有本机副作用，部署走 `npm run deploy`。
	plugins: prod ? [] : [autoDeploy],
});

/**
 * 保守 CSS 压缩：只做「删注释」+「折叠连续空白」两件事。
 *
 *  **不做**选择器/声明级重写（如去掉 `:` `,` `{` 周围空格）——`calc(100% - 2px)`
 *  这类算式**必须保留**运算符两侧空格，去掉会让整条声明非法。所以这里对 CSS
 *  语义零风险，收益来自注释（占 src/styles.css 的 38%）与缩进。回归见
 *  `npm run test:csseq`（真实引擎 CSSOM 逐规则比对）。
 *
 *  `/*!` 开头的许可注释保留。
 */
function minifyCss(css) {
	return css
		.replace(/\/\*[^!][\s\S]*?\*\//g, "")
		.replace(/\s+/g, " ")
		.trim();
}

/** 原子写产物：同目录写临时文件再 `rename`（POSIX 上同目录 rename 是原子的）。
 *
 *  `writeFileSync(out, css)` 是**「截断再写」**：dev watcher 正在重建时若有读者插进来
 *  （`npm run test:csseq` 的校验、Obsidian 加载样式表），会读到**半个文件** —— 症状是
 *  断言报「源与产物归一化后不一致」，单独重跑却是绿的，重跑一百次也复现不了。
 *  用 rename 之后读者只会看到「旧的完整产物」或「新的完整产物」。
 *  顺带消掉一个更小的产品风险：宿主在重建瞬间读到残缺 CSS。 */
function writeCssArtifact(text) {
	const out = "styles.css";
	const tmp = `${out}.tmp-${process.pid}`;
	writeFileSync(tmp, text);
	renameSync(tmp, out);
}

/** src/styles.css（源，作者维护、带注释）→ styles.css（产物，压缩、随插件出货）。
 *
 *  两处刻意为之：
 *  ① **不再先 `copyFileSync` 再原地压缩** —— 那是「一次多余的全量拷贝 + 一次非原子写」，
 *     中间还留着一个「产物已就绪但未压缩」的窗口。直接读源、压缩、原子写出。
 *  ② **体积统一用 `Buffer.byteLength` 口径**。此前日志拿 `before.length`（UTF-16 码元数，
 *     本文件 99,833）去比 `Buffer.byteLength(after)`（字节数），中文注释多的时候两个数
 *     差 28%，报出来的百分比是假的。 */
function buildCss() {
	const src = readFileSync("src/styles.css", "utf8");
	if (process.env.UNREADER_NO_CSS_MIN === "1") {
		writeCssArtifact(src);
		console.log("[css] 跳过压缩（UNREADER_NO_CSS_MIN=1）");
		return;
	}
	const out = minifyCss(src);
	// 幂等闸门：不幂等说明压缩器有状态或顺序问题 —— 宁可让构建失败，也不要发一份
	// 可疑的样式表出去。（当前实现是两条纯正则替换，天然幂等；这条是防未来的改动。）
	if (minifyCss(out) !== out) throw new Error("[css] 压缩器不幂等，拒绝写出 styles.css");
	writeCssArtifact(out);
	const b = (s) => Buffer.byteLength(s, "utf8");
	console.log(`[css] styles.css ${b(src)} → ${b(out)} 字节 (-${(100 - b(out) / b(src) * 100).toFixed(1)}%)`);
}

if (prod) {
	await context.rebuild();
	context.dispose();
	// ⚠️ styles.css 是**构建产物**（源文件是 src/styles.css）：压缩只作用于产物，
	// 源文件保留完整注释供人阅读。改 CSS 请改 src/styles.css。
	buildCss();
} else {
	// dev **也要出产物**。此前 dev 分支只 `context.watch()`，从不写 styles.css ——
	// 而 `src/styles.css` 没有任何模块 import 它（引用全是注释），于是 `npm run dev`
	// 下改 CSS **一点效果都没有**（Obsidian 加载的仍是上一次 prod 构建的旧样式表），
	// 且不会有任何报错提示你。产物陈旧而无人察觉，最终会随 release 出货。
	buildCss();
	// 编辑器保存是「写临时文件 + rename」成对的，60ms 防抖避免读到半截文件；
	// 构建出错只打印、不让 watcher 挂掉（一次语法手误不该终止整个 dev 会话）。
	let cssTimer = null;
	try {
		watch("src/styles.css", () => {
			if (cssTimer) clearTimeout(cssTimer);
			cssTimer = setTimeout(() => {
				try { buildCss(); deployToVaults({ quiet: true }); } catch (e) { console.error("[css]", e instanceof Error ? e.message : e); }
			}, 60);
		});
	} catch (e) {
		console.warn("[css] 无法监听 src/styles.css，改动后请手动跑一次 npm run build", e instanceof Error ? e.message : e);
	}
	await context.watch();
	// 首次 watch 构建是异步的，成功后会经上面的 onEnd 同步；这里补一条可见日志，
	// 免得「产物进没进 vault」又要靠翻文件时间戳才知道。
	console.log(`[deploy] dev watch 已开启自动同步（${deployToVaults({ quiet: true })} 个 vault）`);
}
